name: repo-permission-check
author: zhili(zjutszl@gmail.com)
description: action for permission check 
inputs:
  permission:
    description: ' Least permission user need to access target resource'
    required: true
  files:
    description: ' Check whether the target file has been changed when {path} is provided'
    required: true
outputs:
  pass:
    description: 'Indicate whether user has the right to proceed'
runs:
  using: 'node12'
  main: 'dist/index.js'
